import { getDatabase } from '@/src/db/database';
import type { Project, ProjectDraft } from '@/src/types/project';

type Row = Omit<Project, 'successCriteria' | 'projectManager' | 'startDate' | 'targetDate' | 'createdAt' | 'updatedAt' | 'archived'> & { success_criteria: string; project_manager: string; start_date: string | null; target_date: string | null; created_at: string; updated_at: string; archived: number };
const mapRow = (row: Row): Project => ({ id: row.id, name: row.name, description: row.description, purpose: row.purpose, problem: row.problem, objectives: row.objectives, successCriteria: row.success_criteria, sponsor: row.sponsor, projectManager: row.project_manager, startDate: row.start_date, targetDate: row.target_date, methodology: row.methodology, status: row.status, priority: row.priority, health: row.health, createdAt: row.created_at, updatedAt: row.updated_at, archived: Boolean(row.archived) });
const id = () => globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`;

export const projectRepository = {
  async list(search = ''): Promise<Project[]> { const db = await getDatabase(); const term = `%${search.trim()}%`; const rows = await db.getAllAsync<Row>('SELECT * FROM projects WHERE archived = 0 AND (name LIKE ? OR description LIKE ?) ORDER BY updated_at DESC', [term, term]); return rows.map(mapRow); },
  async get(projectId: string): Promise<Project | null> { const db = await getDatabase(); const row = await db.getFirstAsync<Row>('SELECT * FROM projects WHERE id = ?', [projectId]); return row ? mapRow(row) : null; },
  async create(draft: ProjectDraft): Promise<Project> { const db = await getDatabase(); const now = new Date().toISOString(); const project: Project = { ...draft, id: id(), health: 'Healthy', archived: false, createdAt: now, updatedAt: now }; await db.runAsync('INSERT INTO projects (id,name,description,purpose,problem,objectives,success_criteria,sponsor,project_manager,start_date,target_date,methodology,status,priority,health,archived,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', [project.id, project.name.trim(), project.description.trim(), project.purpose.trim(), project.problem.trim(), project.objectives.trim(), project.successCriteria.trim(), project.sponsor.trim(), project.projectManager.trim(), project.startDate, project.targetDate, project.methodology, project.status, project.priority, project.health, 0, now, now]); return project; },
  async setOnboarded(): Promise<void> { const db = await getDatabase(); await db.runAsync('INSERT OR REPLACE INTO app_settings(key,value) VALUES (?,?)', ['onboardingComplete', 'true']); },
  async isOnboarded(): Promise<boolean> { const db = await getDatabase(); const row = await db.getFirstAsync<{ value: string }>('SELECT value FROM app_settings WHERE key = ?', ['onboardingComplete']); return row?.value === 'true'; },
};
