import { ReactNode } from 'react';
import { Pressable, ScrollView, Text, TextInput, View, useColorScheme } from 'react-native';
import { palette, tokens } from '@/src/lib/design';

export function useTheme() { return palette[useColorScheme() === 'dark' ? 'dark' : 'light']; }
export function Card({ children }: { children: ReactNode }) { const c = useTheme(); return <View style={{ backgroundColor: c.surface, borderColor: c.border, borderWidth: 1, borderRadius: tokens.radius.lg, padding: tokens.space.md, gap: tokens.space.sm, boxShadow: tokens.shadow }}>{children}</View>; }
export function Button({ title, onPress, variant = 'primary', disabled = false, accessibilityLabel }: { title: string; onPress: () => void; variant?: 'primary' | 'secondary'; disabled?: boolean; accessibilityLabel?: string }) { const c = useTheme(); const primary = variant === 'primary'; return <Pressable accessibilityRole="button" accessibilityLabel={accessibilityLabel ?? title} disabled={disabled} onPress={onPress} style={({ pressed }) => ({ backgroundColor: primary ? c.primary : c.tint, paddingVertical: 14, paddingHorizontal: 16, borderRadius: tokens.radius.md, opacity: disabled ? .5 : pressed ? .78 : 1, alignItems: 'center', minHeight: 48 })}><Text style={{ color: primary ? '#fff' : c.primary, fontSize: 16, fontWeight: '700' }}>{title}</Text></Pressable>; }
export function HealthBadge({ health }: { health: string }) { const c = useTheme(); const color = health === 'Healthy' ? c.success : health === 'Critical' ? c.danger : c.warning; return <View accessibilityLabel={`Project health: ${health}`} style={{ alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 5, backgroundColor: c.tint, borderRadius: 99 }}><Text style={{ color, fontWeight: '700', fontSize: 12 }}>{health.toUpperCase()}</Text></View>; }

export function Field({ label, value, onChangeText, multiline = false, placeholder }: { label: string; value: string; onChangeText: (value: string) => void; multiline?: boolean; placeholder?: string }) { const c = useTheme(); return <View style={{ gap: 6 }}><Text selectable style={{ color: c.text, fontWeight: '700' }}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} multiline={multiline} placeholder={placeholder ?? label} placeholderTextColor={c.muted} style={{ minHeight: multiline ? 92 : 48, padding: 12, color: c.text, borderWidth: 1, borderColor: c.border, borderRadius: 12, textAlignVertical: multiline ? 'top' : 'center', backgroundColor: c.surface }} /></View>; }

export function Segmented<T extends string>({ label, options, value, onChange }: { label: string; options: readonly T[]; value: T; onChange: (value: T) => void }) { const c = useTheme(); return <View style={{ gap: 6 }}><Text selectable style={{ color: c.text, fontWeight: '700' }}>{label}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{options.map((option) => { const active = option === value; return <Pressable key={option} accessibilityRole="button" accessibilityLabel={`${label}: ${option}`} accessibilityState={{ selected: active }} onPress={() => onChange(option)} style={{ paddingVertical: 8, paddingHorizontal: 14, borderRadius: 99, backgroundColor: active ? c.primary : c.tint }}><Text style={{ color: active ? '#fff' : c.primary, fontWeight: '700', fontSize: 13 }}>{option}</Text></Pressable>; })}</ScrollView></View>; }

export function EmptyRow({ text }: { text: string }) { const c = useTheme(); return <Text selectable style={{ color: c.muted, fontStyle: 'italic' }}>{text}</Text>; }
